import { useEffect, useState } from "react";
import QRCode from "qrcode";
import { Link, useRoute } from "wouter";
import { BedDouble, Bath, Building2, MapPin, QrCode, Share2, ShieldCheck } from "lucide-react";
import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Button } from "@/components/ui/button";
import { Spinner } from "@/components/ui/spinner";
import { trpc } from "@/lib/trpc";

export default function PublicPropertyShare() {
  const [, params] = useRoute("/share/:identifier");
  const identifier = params?.identifier ?? "";
  const share = trpc.propertySharing.publicLookup.useQuery({ identifier }, { enabled: /^N360-[A-Z]{3}-\d{6}$/.test(identifier), retry: false });
  const [qrUrl, setQrUrl] = useState("");
  const publicUrl = `${window.location.origin}/share/${identifier}`;
  useEffect(() => { if (identifier) QRCode.toDataURL(publicUrl, { width: 150, margin: 1 }).then(setQrUrl).catch(() => setQrUrl("")); }, [identifier, publicUrl]);
  const shareLink = async () => { try { if (navigator.share) await navigator.share({ title: share.data?.property.title ?? "Nyumba 360 property", url: publicUrl }); else await navigator.clipboard.writeText(publicUrl); } catch { /* user cancelled */ } };
  if (share.isLoading) return <div className="grid min-h-screen place-items-center"><Spinner className="h-8 w-8" /></div>;
  if (!share.data) return <div className="min-h-screen bg-slate-50"><Navbar /><main className="container grid min-h-[60vh] place-items-center"><div className="max-w-md text-center"><QrCode className="mx-auto h-12 w-12 text-slate-300" /><h1 className="mt-5 text-3xl font-extrabold">This property sharing link is unavailable</h1><p className="mt-3 text-sm leading-6 text-slate-600">The listing may no longer be approved or public sharing may have been paused.</p><Link href="/properties"><Button className="mt-6 rounded-xl bg-emerald-600 font-bold hover:bg-emerald-500">Explore Nyumba 360</Button></Link></div></main><Footer /></div>;
  const { property, photos } = share.data;
  return <div className="min-h-screen bg-slate-50 text-slate-900"><Navbar /><main className="container py-7 md:py-10"><div className="mx-auto max-w-5xl overflow-hidden rounded-[2rem] border border-slate-200 bg-white shadow-sm"><div className="grid lg:grid-cols-[minmax(0,1.2fr)_minmax(20rem,0.8fr)]">{photos[0]?.url ? <img src={photos[0].url} alt={property.title} className="h-72 w-full object-cover lg:h-full" /> : <div className="grid min-h-72 place-items-center bg-slate-100"><Building2 className="h-12 w-12 text-slate-300" /></div>}<div className="p-6 md:p-8"><div className="flex items-center justify-between gap-3"><span className="rounded-full bg-emerald-50 px-3 py-1 text-xs font-bold text-emerald-700">Public listing</span><Button variant="outline" onClick={shareLink} className="rounded-xl"><Share2 className="mr-2 h-4 w-4" />Share</Button></div><h1 className="mt-5 text-3xl font-extrabold tracking-[-0.04em]">{property.title}</h1><p className="mt-3 flex items-center gap-2 text-sm text-slate-600"><MapPin className="h-4 w-4 text-emerald-600" />{property.location}</p><p className="mt-5 text-3xl font-extrabold text-emerald-700">KSh {Number(property.price).toLocaleString()}<span className="ml-1 text-sm font-medium text-slate-500">{property.listingType === "rent" ? "/ month" : ""}</span></p><div className="mt-6 flex flex-wrap gap-3 text-sm font-bold text-slate-600"><span className="inline-flex items-center gap-1.5 rounded-xl bg-slate-50 px-3 py-2"><BedDouble className="h-4 w-4" />{property.bedrooms} beds</span><span className="inline-flex items-center gap-1.5 rounded-xl bg-slate-50 px-3 py-2"><Bath className="h-4 w-4" />{property.bathrooms} baths</span><span className="inline-flex items-center gap-1.5 rounded-xl bg-slate-50 px-3 py-2 capitalize">{property.propertyType}</span></div><p className="mt-6 line-clamp-4 text-sm leading-6 text-slate-600">{property.description}</p><div className="mt-7 flex items-center gap-3"><Link href={`/property/${property.id}`}><Button className="rounded-xl bg-emerald-600 font-bold hover:bg-emerald-500">View full listing</Button></Link><div className="ml-auto text-right"><p className="font-mono text-xs font-bold text-slate-600">{share.data.identifier}</p>{qrUrl && <img src={qrUrl} alt="Property QR code" className="ml-auto mt-2 h-16 w-16" />}</div></div></div></div><div className="flex items-start gap-3 border-t border-slate-100 bg-slate-50 px-6 py-4 text-xs leading-5 text-slate-600"><ShieldCheck className="mt-0.5 h-4 w-4 shrink-0 text-emerald-600" />This page intentionally shows approved public listing information only. It does not include owner-private data, documents, drafts, or precise map coordinates.</div></div></main><Footer /></div>;
}
