import React from "react";
import { Activity, Database, Loader2, ShieldCheck, TriangleAlert } from "lucide-react";
import { trpc } from "@/lib/trpc";
import { Badge } from "@/components/ui/badge";

export function AdminSystemHealth() {
  const health = trpc.admin.systemHealth.useQuery(undefined, { refetchInterval: 60_000 });
  if (health.isLoading) return <div className="grid min-h-64 place-items-center rounded-3xl border border-slate-200 bg-white"><Loader2 className="h-7 w-7 animate-spin text-emerald-600" /></div>;
  if (!health.data) return <div className="rounded-3xl border border-red-200 bg-red-50 p-5 text-sm text-red-800">System-health data is unavailable. Try refreshing the administrator workspace.</div>;
  const databaseAvailable = health.data.database.status === "available";
  return <div className="space-y-5"><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-3"><div className={`grid h-11 w-11 place-items-center rounded-xl ${databaseAvailable ? "bg-emerald-50 text-emerald-700" : "bg-red-50 text-red-700"}`}><Database className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-emerald-700">Live status check</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.03em] text-slate-950">{health.data.database.label}</h2><p className="mt-1 text-sm text-slate-500">Last checked {new Date(health.data.checkedAt).toLocaleString()}</p></div></div><Badge variant={databaseAvailable ? "default" : "destructive"} className="w-fit capitalize">{health.data.database.status}</Badge></div></section><section className="rounded-3xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><ShieldCheck className="h-5 w-5" /></div><div><p className="text-xs font-bold uppercase tracking-[0.12em] text-emerald-700">Control posture</p><h2 className="mt-1 text-xl font-extrabold tracking-[-0.03em] text-slate-950">Configured platform safeguards</h2></div></div><p className="mt-3 text-sm leading-6 text-slate-500">The cards below describe configuration state, not a complete security certification or external uptime monitor.</p><div className="mt-5 grid gap-3 md:grid-cols-2">{health.data.controls.map((control) => { const isDeferred = control.state === "deferred"; return <article key={control.id} className={`rounded-2xl border p-4 ${isDeferred ? "border-amber-200 bg-amber-50" : "border-emerald-100 bg-emerald-50/50"}`}><div className="flex items-start justify-between gap-3"><p className="font-extrabold text-slate-950">{control.label}</p><Badge variant={isDeferred ? "outline" : "default"} className="capitalize">{control.state}</Badge></div><p className="mt-3 text-sm leading-6 text-slate-600">{control.detail}</p></article>; })}</div></section><section className="rounded-3xl border border-slate-200 bg-slate-950 p-5 text-white shadow-sm"><div className="flex gap-3"><TriangleAlert className="mt-0.5 h-5 w-5 shrink-0 text-lime-300" /><div><p className="font-extrabold">Operational boundary</p><p className="mt-1 text-sm leading-6 text-slate-300">External integrations, deployment infrastructure, and shared high-traffic rate limiting require dedicated provider telemetry or infrastructure configuration. They are not inferred from this application-level status screen.</p></div></div></section></div>;
}
