import React from "react";
import { CalendarDays, FileText, History, Loader2, WalletCards } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";

function StatusBadge({ status }: { status: string }) {
  const tone = status === "completed" || status === "confirmed" ? "default" : status === "pending" ? "outline" : "secondary";
  return <Badge variant={tone} className="capitalize">{status}</Badge>;
}

export function AdminOperationsHub({ data, isLoading, auditFilter, auditQuery, onAuditFilterChange, onAuditQueryChange }: { data: any; isLoading: boolean; auditFilter: "all" | "rejections_with_notes"; auditQuery: string; onAuditFilterChange: (value: "all" | "rejections_with_notes") => void; onAuditQueryChange: (value: string) => void }) {
  if (isLoading) return <div className="grid min-h-64 place-items-center rounded-3xl border border-slate-200 bg-white"><Loader2 className="h-7 w-7 animate-spin text-emerald-600" /></div>;
  const groups = [
    { title: "Recorded payments", description: "Existing payment records only. References are retained as stored; no live settlement is implied.", icon: WalletCards, items: data?.payments ?? [], render: (item: any) => <div className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-900">KSh {Number(item.amount).toLocaleString()} · {item.type.replace("_", " ")}</p><p className="mt-1 text-xs text-slate-500">{item.user?.name || `User #${item.userId}`} · {item.method}</p></div><StatusBadge status={item.status} /></div><p className="mt-2 truncate font-mono text-xs text-slate-500">{item.reference || `Payment #${item.id}`}</p></div> },
    { title: "Upcoming viewings", description: "Pending and confirmed future appointments from the current booking system.", icon: CalendarDays, items: data?.viewings ?? [], render: (item: any) => <div className="rounded-xl border border-slate-100 p-3"><div className="flex items-start justify-between gap-3"><div><p className="font-bold text-slate-900">{item.property?.title || `Property #${item.propertyId}`}</p><p className="mt-1 text-xs text-slate-500">{item.buyer?.name || `Buyer #${item.buyerId}`} · {new Date(item.scheduledAt).toLocaleString()}</p></div><StatusBadge status={item.status} /></div><p className="mt-2 text-xs capitalize text-slate-500">{item.type} viewing</p></div> },
    { title: "Document metadata", description: "Private document file keys and bytes are intentionally unavailable from this summary.", icon: FileText, items: data?.documents ?? [], render: (item: any) => <div className="rounded-xl border border-slate-100 p-3"><p className="truncate font-bold text-slate-900">{item.name}</p><p className="mt-1 truncate text-xs text-slate-500">{item.property?.title || `Property #${item.propertyId}`} · {item.category}</p><p className="mt-2 text-xs text-slate-500">{Math.ceil(item.sizeBytes / 1024)} KB · {new Date(item.createdAt).toLocaleDateString()}</p></div> },
    { title: "Audit activity", description: auditFilter === "rejections_with_notes" ? "Private rejection notes are visible only to administrators in this filtered review." : "Sensitive workflow records from existing module audit logs.", icon: History, items: data?.auditEvents ?? [], controls: <div className="mt-4 grid gap-2 sm:grid-cols-[13rem_minmax(0,1fr)]"><Select value={auditFilter} onValueChange={(value) => onAuditFilterChange(value as "all" | "rejections_with_notes")}><SelectTrigger aria-label="Filter audit activity" className="h-10 rounded-xl"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">All audit activity</SelectItem><SelectItem value="rejections_with_notes">Rejected with notes</SelectItem></SelectContent></Select><Input aria-label="Search private rejection notes" value={auditQuery} onChange={(event) => onAuditQueryChange(event.target.value.slice(0, 80))} disabled={auditFilter !== "rejections_with_notes"} placeholder="Search private rejection notes" className="h-10 rounded-xl" /></div>, render: (item: any) => <div className="rounded-xl border border-slate-100 p-3"><p className="font-bold text-slate-900">{item.action.replace(/[._]/g, " ")}</p><p className="mt-1 text-xs text-slate-500">{item.property?.title || `Property #${item.propertyId || item.resourceId}`} · {item.actor?.name || `Admin #${item.actorUserId}`}</p>{item.moderationNote && <p className="mt-3 rounded-lg bg-amber-50 px-2.5 py-2 text-xs leading-5 text-amber-950"><span className="font-extrabold">Private moderation note:</span> {item.moderationNote}</p>}<p className="mt-2 text-xs text-slate-500">{new Date(item.createdAt).toLocaleString()}</p></div> },
  ];

  return <div className="space-y-6"><div className="rounded-3xl border border-emerald-100 bg-emerald-50/70 p-4 text-sm leading-6 text-emerald-950"><p className="font-extrabold">Operations hub</p><p className="mt-1">This workspace consolidates existing operational records for administrator review. It does not add implied finance, verification, fraud, or document-access capabilities.</p></div><div className="grid gap-5 xl:grid-cols-2">{groups.map(({ title, description, icon: Icon, items, controls, render }) => <section key={title} className="rounded-3xl border border-slate-200 bg-white p-4 shadow-sm md:p-5"><div className="flex items-start gap-3"><div className="grid h-10 w-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="h-5 w-5" /></div><div><h2 className="font-extrabold tracking-[-0.02em] text-slate-950">{title}</h2><p className="mt-1 text-xs leading-5 text-slate-500">{description}</p></div></div>{controls}<div className="mt-4 space-y-2">{items.length ? items.map((item: any) => <div key={item.id}>{render(item)}</div>) : <p className="rounded-xl bg-slate-50 px-3 py-5 text-center text-sm text-slate-500">{title === "Audit activity" && auditFilter === "rejections_with_notes" ? "No rejected properties with private moderation notes match this filter." : "No records available."}</p>}</div></section>)}</div></div>;
}
